doc-valid-idents = [
    "..",
    "BiatNovo",
    "Cascadia",
    "DeepNovo",
    "DeepNovoFamily",
    "EAciD",
    "FragPipe",
    "GNOme",
    "InstaNovo",
    "InstaNovoPlus",
    "MaxNovo",
    "MaxQuant",
    "MetaMorpheus",
    "MSFragger",
    "MzTab",
    "NovoB",
    "OPair",
    "PeakApex",
    "PepNet",
    "PGPointNovo",
    "pi-HelixNovo",
    "pi-PrimeNovo",
    "PLGS",
    "PointNovo",
    "PointNovoFamily",
    "PowerNovo",
    "ProForma",
    "PSM_ID",
    "SpectrumSequenceList",
    "π-HelixNovo",
    "π-PrimeNovo",
]
avoid-breaking-exported-api = false
check-private-items = true
